networks:
  npm_proxy:
    external: true

volumes:
  mongo_data:
  redis_data:

services:
  mongo:
    image: mongo:7
    container_name: bhetghat-mongo
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_ROOT_PASSWORD}
      MONGO_INITDB_DATABASE: bhetghat
    volumes:
      - mongo_data:/data/db

  redis:
    image: redis:7-alpine
    command: redis-server --requirepass ${REDIS_PASSWORD} --appendonly yes
    volumes:
      - redis_data:/data

  livekit:
    image: livekit/livekit-server:latest
    container_name: livekit-server
    network_mode: host
    restart: unless-stopped
    command: --config /livekit.yml
    volumes:
      - ./livekit/livekit.yml:/livekit.yml
    environment:
      LIVEKIT_KEYS: "${LIVEKIT_API_KEY}: ${LIVEKIT_API_SECRET}"

  backend:
    build:
      context: ./backend
    container_name: bhetghat-backend
    restart: unless-stopped
    environment:
      JWT_SECRET: ${JWT_SECRET}
      MONGODB_URI: ${MONGODB_URI}
      LIVEKIT_API_KEY: ${LIVEKIT_API_KEY}
      LIVEKIT_API_SECRET: ${LIVEKIT_API_SECRET}
      LIVEKIT_URL: ${LIVEKIT_URL}
      REDIS_ADDR: ${REDIS_ADDR}
      REDIS_PASSWORD: ${REDIS_PASSWORD}
    depends_on:
      - mongo
      - redis
    networks:
      - default
      - npm_proxy


  frontend:
    build:
      context: ./frontend
      args:
        VITE_GAME_SERVER: https://api.bhetghat.aryabhattarai.com.np
        VITE_GAME_WS: wss://api.bhetghat.aryabhattarai.com.np/ws
        VITE_LIVEKIT_WS: wss://livekit.bhetghat.aryabhattarai.com.np
    container_name: bhetghat-frontend
    restart: unless-stopped
    depends_on:
      - backend
    networks:
      - default
      - npm_proxy
